apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml

namespace: k8s-deviation-production

patchesStrategicMerge:
  - patch-backend.yaml
  - patch-frontend.yaml

images:
  - name: ghcr.io/sb1975/kubernetes-deviation-backend
    newTag: 0.1.0
  - name: ghcr.io/sb1975/kubernetes-deviation-frontend
    newTag: 0.1.0

commonLabels:
  app.kubernetes.io/environment: production
