apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deviation-backend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: APP_ENV
              value: production
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: "1"
              memory: 1Gi
