apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deviation-frontend
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: frontend
          env:
            - name: VITE_ENVIRONMENT
              value: production
