apiVersion: v1
kind: Namespace
metadata:
  name: k8s-deviation
  labels:
    kargo.akuity.io/project: "true"
    app.kubernetes.io/part-of: kubernetes-deviation
    app.kubernetes.io/component: promotion-control-plane
