apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: k8s-deviation-warehouse
  namespace: k8s-deviation
spec:
  interval: 1m
  subscriptions:
    - git:
        repoURL: https://github.com/sb1975/KubernetesDeviationProject.git
        branch: feature/sudeep-code
        path: gitops/apps/k8s-deviation
