apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: k8s-deviation
  namespace: k8s-deviation
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: false
    - stageSelector:
        name: staging
      autoPromotionEnabled: false
    - stageSelector:
        name: production
      autoPromotionEnabled: false
