apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: staging
  namespace: k8s-deviation
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: k8s-deviation-warehouse
      sources:
        stages:
          - dev
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/sb1975/KubernetesDeviationProject.git
            checkout:
              - branch: main
                path: ./src

  verification:
    analysisTemplates:
      - name: verify-staging-api
      - name: verify-staging-ui
      - name: verify-staging-deviation-scan
    args:
      - name: environment
        value: staging
