apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: production
  namespace: k8s-deviation
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: k8s-deviation-warehouse
      sources:
        stages:
          - staging
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/sb1975/KubernetesDeviationProject.git
            checkout:
              - branch: main
                path: ./src

        - uses: kustomize-set-image
          config:
            path: ./src/gitops/apps/k8s-deviation/overlays/production
            images:
              - image: ghcr.io/sb1975/kubernetes-deviation-backend
                tag: ${{ imageFrom("ghcr.io/sb1975/kubernetes-deviation-backend").Tag }}
              - image: ghcr.io/sb1975/kubernetes-deviation-frontend
                tag: ${{ imageFrom("ghcr.io/sb1975/kubernetes-deviation-frontend").Tag }}

        - uses: git-commit
          config:
            path: ./src
            message: "promote(prod): update backend/frontend images"

        - uses: git-push
          config:
            path: ./src
            branch: main

  verification:
    analysisTemplates:
      - name: verify-production-api
      - name: verify-production-ui
      - name: verify-production-deviation-scan
    args:
      - name: environment
        value: production
