apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-deviation-backend
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: APP_ENV
              value: staging
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 600m
              memory: 768Mi
